#
# Azure Pipeline for building the Python wrapper API app
# Build as Docker container image and push to ACR
# Ben C, 2019
#

trigger: none

pool:
  name: Hosted Ubuntu 1604

variables:
  - group: shared-variables
  - group: shared-secrets
  - name: model-name
    value: titanic

steps:
- template: templates/build-image.yaml
