trigger:
  branches:
    include:
    - master
  paths:
    include:
    - notebooks/scikit-titanic.py

queue:
  name: Hosted Ubuntu 1604

variables:
  - group: shared-variables
  - group: shared-secrets

  # Name of the model, used as the blob storage container name
  - name: model-name
    value: titanic

  # Notebook name MUST MATCH THE NAME IN THE JOB
  - name: notebook-name
    value: scikit-titanic   
  
  # DataBricks job-name
  - name: job-name
    value: train-titanic-model
  
  # Don't change this
  - name: job-params
    value: '{ "model_version":"$(version)", "model_name":"$(model-name)", "storage_account":"$(storage-account)" }'
    
steps:
- template: templates/run-databricks-job.yaml
