#
### Change host as required
#
@host = localhost:7071

#
### Get model API parameters
#
GET http://{{host}}/api/predict/params

#
### Call the model for a prediction
#
POST http://{{host}}/api/predict
Content-Type: application/json

{
  "force": "Kent Police",
  "crime": "Drugs",
  "month": 4
}