#
### Change host as required
#
@host = localhost:7071
#@host = modelpredict.azurewebsites.net
@code = 
#@code = phf0AqooWf5495qHqGZ4Gx5KKfz2/hJ1XKM89rv6/wFEBLJDl3yKqQ==

#
### Get model API parameters
#
GET http://{{host}}/api/predict/params?code={{code}}

#
### Call the model for a prediction
#
POST http://{{host}}/api/predict
Content-Type: application/json

{
  "force": "Kent Police",
  "crime": "Burglary",
  "month": 10
}