#
# Default values for Smilr Helm chart
#

# Change to blank string to pull from Docker Hub
registryPrefix: 

# Leave blank if not using DNS with your ingress
domainName: 

# Change if not using AKS with HTTP routing 
ingressClass: addon-http-application-routing

# If using cert-manager to issue TLS certs for HTTPS support 
# Leave blank if you haven't set up cert-manager to disable HTTPS
# certName should be blank
cmCertIssuer: 

# If you have a static cert for domainName in a secret, put it here
# cmCertIssuer should be blank
certName:

api:
  image: 
  replicas: 1
  imagePullPolicy: Always
  modelVersion: 1
