trigger:
  branches:
    include:
    - master
  paths:
    include:
    - training/scikit-batcomputer.py
    - pipelines/batcomputer-training.yml
    - aml/run-training.py

queue:
  name: Hosted Ubuntu 1604

variables:
  # shared-variables group MUST contain: AZML_WORKSPACE, AZML_SUBID, AZML_RESGRP, AZML_COMPUTE_NAME
  - group: shared-variables

  - name: AZML_DATAPATH
    value: batcomputer-data

  - name: AZML_MODEL
    value: batcomputer-model

  - name: AZML_EXPERIMENT
    value: batcomputer

  - name: AZML_SCRIPT
    value: scikit-batcomputer.py

jobs:
- job: runTraining
  displayName: Train model in Azure ML 

  steps:
  - task: UsePythonVersion@0
    displayName: Use Python 3.6
    inputs:
      versionSpec: '3.6'
      addToPath: true 

  - bash: |
      pip3 install -r requirements.txt
    workingDirectory: aml
    displayName: Install pip package requirements

  - task: AzureCLI@1
    displayName: Run AML training script
    inputs:
      azureSubscription: $(AZURE_SVC_CONNECTION)
      scriptLocation: inlineScript
      inlineScript: python run-training.py --estimators 120
      workingDirectory: aml