trigger: none
pr: none

variables:
  # shared-variables group MUST contain: AZML_WORKSPACE, AZML_SUBID, AZML_RESGRP
  - group: shared-variables

  - name: AZML_DATAPATH
    value: batcomputer-data

jobs:
- job: loadData
  displayName: Load crime data into Azure ML
  pool:
    vmImage: ubuntu-latest

  steps:
  - bash: |
      wget https://bcmisc.blob.core.windows.net/shared/crime.zip -O data/batcomputer/crime.zip
    displayName: Download crime data from Blob store

  - task: UsePythonVersion@0
    displayName: Use Python 3.6
    inputs:
      versionSpec: '3.6'
      addToPath: true 

  - bash: |
      pip3 install -r requirements.txt
    workingDirectory: aml
    displayName: Install pip package requirements

  - task: AzureCLI@1
    displayName: Run AML upload data script
    inputs:
      azureSubscription: $(AZURE_SVC_CONNECTION)
      scriptLocation: inlineScript
      inlineScript: python upload-data.py --data-dir ../data/batcomputer
      workingDirectory: aml