registryPrefix: bencmldemo3408602738.azurecr.io/
domainName: batcomputer.kube.benco.io
#cmCertIssuer: letsencrypt-staging

api:
  image: batcomputer-model-api
  replicas: 1
  imagePullPolicy: Always
  modelVersion: 1